# Global project config
project_name: "Geo_Sentiment_Climate"

# Data ingestion config
paths:
  raw_dir: "../data/raw/"
  interim_dir: "../data/interim/"
  processed_dir: "../data/processed/"
  metadata_dir: "../data/metadata/"
  plots_dir: "../plots/"
  logs_dir: "../logs/"
  archive_dir: "../data/archive/"


# Parameter rename map example
rename_map_common:
  "Date": "date"
  "Units": "units"
  "Daily AQI Value": "aqi"
  "State FIPS Code": "state_fips"
  "County FIPS Code": "county_fips"

# Param specific rename
rename_map_param:
  so2: "Daily Max 1-hour SO2 Concentration"
  o3: "Daily Max 8-hour Ozone Concentration"
  co: "Daily Max 8-hour CO Concentration"
  no2: "Daily Max 1-hour NO2 Concentration"
  pm25: "Daily Mean PM2.5 Concentration"

# Required columns for data check
data_check:
  required_columns:
    - Date
    - Source
    - Site ID
    - POC
    - Daily Max 1-hour SO2 Concentration
    - Units
    - Daily AQI Value
    - Local Site Name
    - Daily Obs Count
    - Percent Complete
    - AQS Parameter Code
    - AQS Parameter Description
    - Method Code
    - CBSA Code
    - CBSA Name
    - State FIPS Code
    - State
    - County FIPS Code
    - County
    - Site Latitude
    - Site Longitude
  optional_columns:
    - "Source"
    - "Site ID"
    - "POC"
    - "Local Site Name"
    - "Daily Obs Count"
    - "Percent Complete"
    - "Method Code"
    - "CBSA Code"
    - "CBSA Name"
    - "State FIPS Code"
    - "County FIPS Code"

parameters:
  missing_value_method: "mean"
  scaling_method: "standard"
  max_rows: 5000

eda:
  numeric_threshold: 0.75
  max_categories: 20

logging:
  log_file: "../logs/project.log"
  log_level: "INFO"
  log_format: "%(asctime)s - %(levelname)s - %(message)s"