# settings.yml

# Global project config
project_name: "Geo_Sentiment_Climate"

# Data ingestion config
data:
  raw_dir: "../data/raw/"
  interim_dir: "../data/interim/"
  processed_dir: "../data/processed/"

# Parameter rename map example
rename_map_common:
  "Date": "date"
  "Units": "units"
  "Daily AQI Value": "aqi"
  "State FIPS Code": "state_fips"
  "County FIPS Code": "county_fips"

# Param specific rename
rename_map_param:
  so2: "Daily Max 1-hour SO2 Concentration"
  o3: "Daily Max 8-hour Ozone Concentration"
  co: "Daily Max 8-hour CO Concentration"
  no2: "Daily Max 1-hour NO2 Concentration"
  pm25: "Daily Mean PM2.5 Concentration"

# config path
paths:
  raw_dir: "../source/data/raw"
  processed_dir: "../source/data/processed"
  plots_dir: "../plots"
  logs_dir: "../logs"

# Required columns for data check
required_columns:
  - "Date"  # Zaman bilgisi (tarih)
  - "Daily Max 1-hour SO2 Concentration"  # Temel analiz metriği
  - "Units"  # Metriğin birimi (ppm, µg/m³ vb.)
  - "Site Latitude"  # Coğrafi konum bilgisi
  - "Site Longitude"  # Coğrafi konum bilgisi
  - "AQS Parameter Code"  # Parametre tanımı için kod
  - "State"  # Eyalet bilgisi
  - "County"  # İlçe bilgisi
  - "Daily AQI Value"  # AQI (Hava Kalite İndeksi) analizi


optional_columns:
  - "Source"
  - "Site ID"
  - "POC"
  - "Local Site Name"
  - "Daily Obs Count"
  - "Percent Complete"
  - "Method Code"
  - "CBSA Code"
  - "CBSA Name"
  - "State FIPS Code"
  - "County FIPS Code"

  parameters:
    missing_value_method: "mean"
    scaling_method: "standard"
    max_rows: 5000

eda:
  numeric_threshold: 0.75  # Örneğin, bir korelasyon eşiği belirlemek için
  max_categories: 20       # Kategorik sütunlar için analiz limiti

logging:
  log_file: "../logs/project.log"
  log_level: "INFO"
  log_format: "%(asctime)s - %(levelname)s - %(message)s"
